<a href="https://colab.research.google.com/github/fattrovi/24k/blob/master/blablabla2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
#round

# **情境** 
Kenny有一艘屬於他的小船，但是放船的門不小心被上鎖了，門口的密碼需要他解出陣列才能破解，於是他靜下心來，努力回想最近剛學的python來解決問題:

In [2]:
x = np.array([[3,8,7],
              [5,8,4],
              [2,3,3]])
x.shape

(3, 3)

In [3]:
y = np.linalg.inv(x)
y.round() + 0

array([[ 0.,  0.,  1.],
       [ 0.,  0., -1.],
       [ 0.,  0.,  1.]])

In [4]:
c = x@y
c.round() + 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.allclose(c,np.eye(3))

True

In [6]:
(x+y).round() + 0

array([[3., 8., 8.],
       [5., 8., 3.],
       [2., 3., 4.]])

Kenny經過了一番計算並驗證後，成功獲得密碼388583234打開了門，結果發現裡面空空如也，只看到地上一張紙寫著 **SB** ，並發出了悲憤地咆哮。

## THE END